polygon_pass_opposite_line_time_measurer:
  ros__parameters:
    vehicle_length: 7.24
    vehicle_width: 2.30
    base_link_to_center_offset: 2.19

    shiojiri:
      city_hall_entrance:
        start_line_p1_x: 65779.1159
        start_line_p1_y: 723.4907
        start_line_p2_x: 65779.6364
        start_line_p2_y: 746.2223
        finish_line_p1_x: 65782.851
        finish_line_p1_y: 723.4006
        finish_line_p2_x: 65783.3713
        finish_line_p2_y: 746.1353
      reference_intersection:
        start_line_p1_x: 65778.1527
        start_line_p1_y: 682.7994
        start_line_p2_x: 65777.6611
        start_line_p2_y: 661.6699
        finish_line_p1_x: 65774.2231
        finish_line_p1_y: 682.8651
        finish_line_p2_x: 65773.7878
        finish_line_p2_y: 661.694
    komatsu:
      saikucho:
        start_line_p1_x: 30085.29
        start_line_p1_y: 29948.04
        start_line_p2_x: 30150.67
        start_line_p2_y: 29942.49
        finish_line_p1_x: 30084.98
        finish_line_p1_y: 29942.15
        finish_line_p2_x: 30150.18
        finish_line_p2_y: 29936.40
    shinkiba:
      station_return:
        start_line_p1_x: 93842.24
        start_line_p1_y: 45177.01
        start_line_p2_x: 93804.53
        start_line_p2_y: 45173.53
        finish_line_p1_x: 93841.18
        finish_line_p1_y: 45185.33
        finish_line_p2_x: 93803.90
        finish_line_p2_y: 45181.41
      shinkiba_wakasu_line:
        start_line_p1_x: 94710.14
        start_line_p1_y: 45266.25
        start_line_p2_x: 94775.04
        start_line_p2_y: 45268.03
        finish_line_p1_x: 94710.84
        finish_line_p1_y: 45257.27
        finish_line_p2_x: 94774.80
        finish_line_p2_y: 45264.15
      uminomori_park:
        start_line_p1_x: 91730.63
        start_line_p1_y: 40365.74
        start_line_p2_x: 91706.38
        start_line_p2_y: 40398.20
        finish_line_p1_x: 91736.45
        finish_line_p1_y: 40369.69
        finish_line_p2_x: 91712.39
        finish_line_p2_y: 40402.61


